### ISSUE TITLE
Audience validity where multiple audience values exist

### ISSUE THREAD

**Issue by joshdcollins** [solid/identity-token-verifier#3]
Given a JWT with multiple audience values (in an array), the verifier currently rejects the token as having an invalid audience.

```
{
  ....
  "aud": [
    "solid",
    "account"
  ],
  ....
```

Should the verification logic be this restrictive or should it just ensure, if an array, that solid is one of the values?

I'm thinking of scenarios where an IdP is looking to support Solid while accommodating other, existing schemes that may also expect certain audience values.

**Comment by matthieubosquet** [comment]
I'm not sure, @acoburn do you have an opinion on that question?

**Comment by acoburn** [comment]
An audience claim can be either a single string or a list. If it's a list, then the typical pattern around audience claims is to check for containment. 

The [Solid-OIDC spec](https://solid.github.io/authentication-panel/solid-oidc/#tokens-access) reads: 

> aud — REQUIRED. The audience claim MUST be the string solid.

but I wonder if that is too restrictive. In token validation code that I have written, I check for containment. In token generation code that I have written, I produce a single string.

**Comment by matthieubosquet** [comment]
I'm not sure what the use case for several audiences would be?

I thought that Solid OIDC was especially designed to interact with servers using the Solid Protocol, hence an audience of "solid" makes sense to me. I wouldn't expect to be using the same token in a different context.

But maybe I'm just not thinking of the use cases.

**Comment by matthieubosquet** [comment]
Spec was clarified to accomodate multiple audience values: https://github.com/solid/authentication-panel/pull/141

**Comment by matthieubosquet** [comment]
Thanks @joshdcollins for raising this!

:)

It now should be fixed and published in v0.6.3 of the library.

https://github.com/solid/identity-token-verifier/pull/5
