### ISSUE TITLE
UrlClaim verifier enforces https scheme, which precludes localhost issuer/webid

### ISSUE THREAD

**Issue by woutermont** [solid/identity-token-verifier#4]
The `urlClaim` verifier function in `AccessToken.ts`, which is called for issuer and webid claims in the token, throws an error as soon as the urls do not have the `https` scheme. I believe this is a practical way to enforce TLS, but it has the side-effect that `localhost` urls fail as well.

Would there be something againt making an exception for `localhost` urls?

**Comment by woutermont** [comment]
Ha, woops, hadn't pulled in your latest commit (7e18d86) while writing the same fix, @matthieubosquet 😄

**Comment by matthieubosquet** [comment]
😄 the two of us fixing the same thing within 24 hours
